INSERT INTO ADMIN (account, password, name, privilege, status, is_default_pwd, create_time, update_time, updater) VALUES ( 'admin', '0000', '系統管理員', 1, 0, 0, curdate(), curdate(), 1);
INSERT INTO PRIVILEGE(name,status,privilege_level, create_time,update_time,updater)VALUES('系統管理員',0, 1, curdate(),curdate(),1);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,1);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,2);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,3);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,4);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,5);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,6);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,7);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,8);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,9);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,10);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,11);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,12);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,13);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,14);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,15);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,16);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,17);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,18);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,19);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,20);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,21);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,22);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,23);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,24);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,25);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,26);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,27);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,28);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,29);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,30);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,31);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,32);
INSERT INTO PRIVILEGE_FUNC_PERMISSION_MAPPING(privilege_id, func_permission_id)VALUES(1,33);
commit;